### ISSUE TITLE
Proposal to create a Laravel Package for this library

### ISSUE THREAD

**Issue by eldomagan** [TunkShif/alpine-zag#1]
I was thinking of creating an alpine version of ArkUI and just found your project. well done on the amazing work. 

I want to create a Laravel package that wraps that wrap your library for easier integration into Laravel applications. Before proceeding, I wanted to ask if you have any plans to create an official Laravel package yourself. If not, would you be open to me building and maintaining this package?

**Comment by TunkShif** [comment]
Hi, I'm glad to hear that you found this project helpful. I originally created it for use with the Elixir Phoenix Framework, and I don't have any plans to create a Laravel package myself, as I don't have much experience with Laravel. So feel free to create and maintain your own package based on this project.

**Comment by eldomagan** [comment]
Thank you.
